name: Testing GitHub Actions

on: workflow_dispatch

env:
  UNY_AUTO_PAT: ${{ secrets.UNY_AUTO_PAT }}
  GH_TOKEN: ${{ secrets.UNY_AUTO_PAT }}

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Save variables to files
        run: |
          echo "$UNY_AUTO_PAT" >UNY_AUTO_PAT
          echo "$GH_TOKEN" >GH_TOKEN
      - name: Run job 1
        run: |
          chmod +x script.sh
          sudo ./script.sh
